name: Crear EXE Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Crear ejecutable
        run: |
          pyinstaller TallerMotos.spec

      - name: Guardar EXE
        uses: actions/upload-artifact@v4
        with:
          name: Taller Motos Windows
          path: dist/
